name: linux-capabilities
version: 1.1.0.0
synopsis: Low-level interface to capabilities(7)
description: |
  Linux capabilities are more fine-grained implementation of idea of suid-root
  binaries, granting executable only subset of powers normally associated with
  root. They are set by writing into "security.capability" extended attribute
  binary string of specific format.

  This library provides idiomatic interface for capability set, as well
  as function to convert it into bytestring to be written into extended
  attribute.

  Check bare-bones re-implementation of "setcap" utility as example:
  <https://git.sr.ht/~kaction/linux-capabilities/tree/master/item/Main.hs>
author: Dmitry Bogatov
git: https://git.sr.ht/~kaction/linux-capabilities
category: System.Linux
license: AGPL-3.0-or-later

dependencies:
  - base >=4.11 && < 5
  - text
  - bytestring

library:
  source-dirs: src
  generated-other-modules:
    - Paths_linux_capabilities

executables:
  hs-setcap:
    main: Main.hs
    dependencies:
      - base
      - split
      - text
      - bytestring
      - xattr
      - lens
      - linux-capabilities
